const actionTypes = Object.freeze({
    //user
    SAVE_USERS_TO_REDUX_LOCAL_STORE: 'SAVE_USERS_TO_REDUX_LOCAL_STORE',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    SET_NAVIGATE_URL: 'SET_NAVIGATE_URL',
});

export default actionTypes;
